service: email-micro-service

plugins:
  - serverless-offline

custom:
  tableName: 'email-micro-service-${self:provider.stage}'

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    OCCUPATION_TABLE: ${self:custom.tableName}

functions:

  emailConfirmation:
    handler: handler.emailConfirmation
    name: ${self:provider.stage}-emailConfirmation
    description: email confirmation for the order creation
    events:
      - http: 
          path: emailConfirmation
          method: get
          cors: 
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - X-Amz-Security-Token
            allowCredentials: true
